=== api-evangelist/hunter/json-schema/hunter-company-geo-location-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "CompanyGeoLocation",
  "type": "object",
  "properties": {
    "streetNumber": {
      "type": "['string', 'null']"
    },
    "streetName": {
      "type": "['string', 'null']"
    },
    "subPremise": {
      "type": "['string', 'null']"
    },
    "streetAddress": {
      "type": "['string', 'null']"
    },
    "city": {
      "type": "['string', 'null']"
    },
    "postalCode": {
      "type": "['string', 'null']"
    },
    "state": {
      "type": "['string', 'null']"
    },
    "stateCode": {
      "type": "['string', 'null']"
    },
    "country": {
      "type": "['string', 'null']"
    },
    "countryCode": {
      "type": "['string', 'null']"
    },
    "lat": {
      "type": "['number', 'null']"
    },
    "lng": {
      "type": "['number', 'null']"
    }
  }
}

=== api-evangelist/hunter/examples/hunter-company-geo-location-example.json
{
  "streetNumber": "example_value",
  "streetName": "example_value",
  "subPremise": "example_value",
  "streetAddress": "example_value",
  "city": "example_value",
  "postalCode": "example_value",
  "state": "example_value",
  "stateCode": "example_value",
  "country": "example_value",
  "countryCode": "example_value",
  "lat": "example_value",
  "lng": "example_value"
}
